version: '3.4'

services:

  # rabbitmq-server
  rabbitmq-server:
    image: rabbitmq:3-management
    hostname: "my-rabbit"
    ports:
      # host:container
      - "15672:15672"
      - "5672:5672"
    volumes:
      - type: volume
        source: rabbitmqdb
        target: /var/lib/rabbitmq 

  eurekaserver:
    image: gutenberg/eureka-service
    ports:
      - "8761:8761"

  zipkin-server:
    image: gutenberg/zipkinsvr
    ports:
      - "9411:9411"

  config-server:
    image: gutenberg/config-server
    # edit to match your own filesystem
    volumes:
      - type: bind
        source: /home/dominique/gutenberg-sleuth/config-repo
        target: /tmp/config-repo
    ports:
      - "8888:8888"
    environment:
      - EUREKASERVER_URI=http://eurekaserver:8761/eureka/
      - EUREKASERVER_HOST=eurekaserver
      - EUREKASERVER_PORT=8761
 

  # books-mongodb 
  books-mongodb:
    image: mongo
    volumes:
      - type: volume
        source: booksdb
        target: /data/db 
    # Note mongod not mongo because we start a server not a client      
    command: mongod --smallfiles --auth
    ports:
      # Note the syntax host:container
      - 28017:27017
    restart: always



  book-service:
    image: gutenberg/book-server
    ports:
      - 8081:8081
    environment:
      - GUTENBERG_CONFIG_URI=http://config-server:8888
      - CONFIGSERVER_HOST=config-server
      - CONFIGSERVER_PORT=8888
      - RABBITMQSERVER_HOST=rabbitmq-server
      - RABBITMQSERVER_PORT=5672
      - MONGODBSERVER_HOST=books-mongodb
      - MONGODBSERVER_PORT=27017

  
  user-service:
    image: gutenberg/user-server
    ports:
      - 8084:8084
    environment:
      - GUTENBERG_CONFIG_URI=http://config-server:8888
      - CONFIGSERVER_HOST=config-server
      - CONFIGSERVER_PORT=8888
      - RABBITMQSERVER_HOST=rabbitmq-server
      - RABBITMQSERVER_PORT=5672
      - MONGODBSERVER_HOST=books-mongodb
      - MONGODBSERVER_PORT=27017

  review-service:
    image: gutenberg/review-server
    ports:
      - 8082:8082
    environment:
      - GUTENBERG_CONFIG_URI=http://config-server:8888
      - CONFIGSERVER_HOST=config-server
      - CONFIGSERVER_PORT=8888
      - RABBITMQSERVER_HOST=rabbitmq-server
      - RABBITMQSERVER_PORT=5672
      - MONGODBSERVER_HOST=books-mongodb
      - MONGODBSERVER_PORT=27017

  order-service:
    image: gutenberg/order-server
    ports:
      - 8083:8083
    environment:
      - GUTENBERG_CONFIG_URI=http://config-server:8888
      - CONFIGSERVER_HOST=config-server
      - CONFIGSERVER_PORT=8888
      - RABBITMQSERVER_HOST=rabbitmq-server
      - RABBITMQSERVER_PORT=5672
      - MONGODBSERVER_HOST=books-mongodb
      - MONGODBSERVER_PORT=27017

  zuul-service:
    image: gutenberg/zuul-server
    ports:
      - 5555:5555
    environment:
      - GUTENBERG_CONFIG_URI=http://config-server:8888
      - CONFIGSERVER_HOST=config-server
      - CONFIGSERVER_PORT=8888
      - RABBITMQSERVER_HOST=rabbitmq-server
      - RABBITMQSERVER_PORT=5672
      - MONGODBSERVER_HOST=books-mongodb
      - MONGODBSERVER_PORT=27017

  # redis-service
  redis-service:
    image: redis
    #ports:
      # host:container
      #- 6379:6379

  frontend-server:
    image: gutenberg/frontend-server
    ports:
      - 8080:8080
    environment:
      - GUTENBERG_CONFIG_URI=http://config-server:8888
      - CONFIGSERVER_HOST=config-server
      - CONFIGSERVER_PORT=8888
      - RABBITMQSERVER_HOST=rabbitmq-server
      - RABBITMQSERVER_PORT=5672
      - MONGODBSERVER_HOST=books-mongodb
      - MONGODBSERVER_PORT=27017
      - BOOKSERVER_HOST=book-service
      - BOOKSERVER_PORT=8081
      - USERSERVER_HOST=user-service
      - USERSERVER_PORT=8084
      - REVIEWSERVER_HOST=review-service
      - REVIEWSERVER_PORT=8082
      - ORDERSERVER_HOST=order-service
      - ORDERSERVER_PORT=8083


  # admin-service
  admin-service:
    image: gutenberg/admin-server
    depends_on:
      - config-server
      - books-mongodb
    ports:
      # host:container
      - 9090:9090
    environment:
      - CONFIGSERVER_HOST=config-server
      - CONFIGSERVER_PORT=8888
      - BOOKSERVER_HOST=book-service
      - BOOKSERVER_PORT=8081
      - ORDERSERVER_HOST=order-service
      - ORDERSERVER_PORT=8083
      - GUTENBERG_CONFIG_URI=http://config-server:8888
      - PROFILE=dev

volumes:
  booksdb:
    external: 
      name: gutenberg-books-db
  rabbitmqdb:
    external: 
      name: gutenberg-rabbitmq-db 

 

